homepage: "www.pjsip.org"
language: c
primary_contact: "security@pjsip.org"
vendor_ccs:
  - "Nanang mail on"
auto_ccs:
  - "ajsinghyadav00@gmail.com"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
sanitizers:
  - address
  - memory
  - undefined
main_repo: 'https://github.com/pjsip/pjproject'
