homepage: "https://github.com/twitter/twemproxy"
language: c
primary_contact: "security@twitter.com"
auto_ccs:
  - "ajsinghyadav00@gmail.com"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
sanitizers:
  - address
  - memory
  - undefined
main_repo: 'https://github.com/twitter/twemproxy'
