homepage: "https://github.com/gosnmp/gosnmp"
language: go
primary_contact: "tim.rots@protonmail.ch"
auto_ccs:
  - "ajsinghyadav00@gmail.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
main_repo: "https://github.com/gosnmp/gosnmp"
