homepage: "https://github.com/coturn/coturn"
language: c
primary_contact: "misi@majd.eu"
vendor_ccs:
  - "mom040267@gmail.com"
auto_ccs:
  - "ajsinghyadav00@gmail.com"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
sanitizers:
  - address
  - memory
  - undefined
main_repo: 'https://github.com/coturn/coturn'
