homepage: "https://ntpsec.org/"
language: c
primary_contact: "fallenpegasus@gmail.com"
vendor_ccs:
  - "security@ntpsec.org"
  - "contact@ntpsec.org"
auto_ccs:
  - "ajsinghyadav00@gmail.com"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
sanitizers:
  - address
  - memory
  - undefined
main_repo: 'https://gitlab.com/NTPsec/ntpsec'
