homepage: "https://brpc.apache.org"
language: c++
primary_contact: "security@apache.org"
auto_ccs:
  - "ajsinghyadav00@gmail.com"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
sanitizers:
  - address
  - memory
main_repo: 'https://github.com/apache/incubator-brpc'
