homepage: "https://www.magmacore.org/"
language: c++
primary_contact: "security@lists.magmacore.org"
auto_ccs:
  - "ajsinghyadav00@gmail.com"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
sanitizers:
  - address
main_repo: 'https://github.com/magma/magma.git'
