homepage: "www.zabbix.com"
language: c
primary_contact: "security@zabbix.com"
auto_ccs:
  - "ajsinghyadav00@gmail.com"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
sanitizers:
  - address
  - memory
  - undefined
main_repo: 'https://github.com/zabbix/zabbix'
